<?php
namespace App\Controll\admin;

use App\Module\UserModule;

class Login extends Base{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->userId){
            $this->redirect("admin/Admin/index");
        }
    }

    public function login(){
        $this->template->assign('config_front',$this->config_front);
        $this->template->display('admin/login.php');
    }

    public function doLogin(){
        $userName = $this->request->post('userName');
        $password = $this->request->post('password');
        $password = md5($password);

        $userModule = new UserModule();
        $userInfo = $userModule->infoByUsername($userName);

        if(empty($userInfo)){
            $this->alertLocation('/admin/Login/login','用户名或者密码错误');
        }

        if($userInfo['password'] == $password){
            $this->session->setSession("userId",$userInfo['id']);
            $this->alertLocation('/admin/Admin/index','登录成功');
        }else{
            $this->alertLocation('/admin/Login/login','用户名或者密码错误');
        }
    }
}